# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f033e7bf47c3b2bb1676b94305fa0b092c728b278e7b67722d48f6757b15523b02031d9dfbcc0d4eddab7802e2cec261ca3a49741a1fbd0a1560e5f2e6643b2

test:
  secret_key_base: 0d727d918395bd949d19590b9aa75bde3350f6cf72d75bc1d5724c38aa16c3a28f44fc3f1addcf879ceb2defd1ab9fe1a22aeaf5a1d90feb85baeaaf4d51c2f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
